node {
    checkout scm

    env.DOCKER_API_VERSION="1.23"
    
    sh "git rev-parse --short HEAD > commit-id"

    tag = "v"+readFile('commit-id').replace("\n", "").replace("\r", "")
    appName = "mean-k8s"
    registryHost = "127.0.0.1:30400/"
    imageName = "${registryHost}${appName}:${tag}"
    env.BUILDIMG=imageName

    stage "Build"
    
        sh "docker build -t ${imageName} -f applications/${appName}/Dockerfile applications/${appName}"
    
    stage "Push"

        sh "docker push ${imageName}"

    stage "Deploy"

        sh """
            helm upgrade --install \
                --set image.repository=${registryHost}${appName},image.tag=${tag} ${appName} applications/${appName}/helm-chart/
        """
}